BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "students" (
	"num"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"student_id"	INTEGER NOT NULL,
	"major_id"	INTEGER NOT NULL,
	"name"	INTEGER NOT NULL,
	"phone"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "majors" (
	"num"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"major_id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	"credits"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "logins" (
	"num"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"login_id"	INTEGER NOT NULL,
	"email"	TEXT NOT NULL,
	"password"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "teachers" (
	"num"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"teacher_id"	INTEGER NOT NULL,
	"major_id"	INTEGER NOT NULL,
	"name"	INTEGER NOT NULL,
	"phone"	INTEGER NOT NULL
);
INSERT INTO "students" VALUES (1,2016089,1,'Bilguun',99197611);
INSERT INTO "students" VALUES (2,2016133,2,'Banzragch',88082535);
INSERT INTO "students" VALUES (3,2017098,3,'Someone',12312312);
INSERT INTO "majors" VALUES (1,1,'CS',120);
INSERT INTO "majors" VALUES (2,2,'IM',120);
INSERT INTO "majors" VALUES (3,3,'HM',120);
INSERT INTO "logins" VALUES (1,2016089,'bilguun@yahoo.com','abc123');
INSERT INTO "logins" VALUES (2,2016133,'banzragch@yahoo.com','cba123');
INSERT INTO "logins" VALUES (3,2017098,'someone@yahoo.com','acb321');
INSERT INTO "teachers" VALUES (1,111,1,'Moon Bae',99999999);
INSERT INTO "teachers" VALUES (2,123,2,'Hai Bill',12312333);
INSERT INTO "teachers" VALUES (3,132,3,'James Bonderino',12312312);
COMMIT;
